### ISSUE TITLE
Error generating code after node removal

### ISSUE THREAD

**Issue by fonkap** [estools/escodegen#348]
I'm trying to regenerate code after removing a node using "estraverse" but I get an error.

The code I'm using is:

    var esprima = require('esprima');
    var estraverse = require('estraverse');
    var escodegen = require('escodegen');

    (function () {
    //build an ast with 2 lines of code
    var ast = esprima.parse("console.log('1');\n console.log('2');")
    console.log("original code:\n" + escodegen.generate(ast));
    console.log();

    //change one of the lines, works
    ast = estraverse.replace(ast, {
      enter: function (node) {
      },
      leave: function (node) {
        if (node.type === esprima.Syntax.CallExpression) {
          this.break();
          return esprima.parse("console.log('patch');").body[0].expression;
        }
      }
    });
    console.log("patched code:\n" + escodegen.generate(ast));
    console.log();

    //remove one of the lines, error
    ast = estraverse.replace(ast, {
      enter: function (node) {
      },
      leave: function (node) {
        if (node.type === esprima.Syntax.CallExpression) {
          this.break();
          return this.remove();
        }
      }
    });
    console.log("removed node:\n" + escodegen.generate(ast));
    })()

The error trace is:

    C:\temp\node_modules\escodegen\escodegen.js:2450
            type = expr.type || Syntax.Property;
                      ^

    TypeError: Cannot read property 'type' of null
        at CodeGenerator.generateExpression (C:\temp\node_modules\escodegen\escodegen.js:2450:20)
        at CodeGenerator.ExpressionStatement (C:\temp\node_modules\escodegen\escodegen.js:1335:28)
        at CodeGenerator.generateStatement (C:\temp\node_modules\escodegen\escodegen.js:2469:33)
        at CodeGenerator.Program (C:\temp\node_modules\escodegen\escodegen.js:1717:43)
        at CodeGenerator.generateStatement (C:\temp\node_modules\escodegen\escodegen.js:2469:33)
        at generateInternal (C:\temp\node_modules\escodegen\escodegen.js:2490:28)
        at Object.generate (C:\temp\node_modules\escodegen\escodegen.js:2558:18)
        at C:\temp\bug1.js:35:45
        at Object.<anonymous> (C:\temp\bug1.js:38:3)
        at Module._compile (module.js:570:32)

Am I doing something wrong? Is this an error in "escodegen" or maybe in "estraverse"?

Thanks in advance.

**Comment by michaelficarra** [comment]
You've generated an invalid AST. ExpressionStatement nodes must have a non-null expression, but you've removed it. Next time, when reporting a bug, just include your input and expected/actual outputs. All of this estraverse stuff just distracts.

**Comment by fonkap** [comment]
Thank you for your response Michael,
If I delete an ExpressionStatement instead of a CallExpression it works. Makes sense.

Thanks again.
