### ISSUE TITLE
Support optional catch binding

### ISSUE THREAD

**Issue by cixel** [estools/escodegen#382]
Support this [Stage 4 proposal](https://github.com/tc39/proposal-optional-catch-binding) to allow omission of `catch` variable in cases where the error is unused:
```javascript
try {
  // ...
} catch {
  // ...
}
```

See [Why?](https://github.com/tc39/proposal-optional-catch-binding/issues/2) for justification and more details.

This has already been implemented in [v8 6.6](https://v8.dev/blog/v8-release-66) and is available in recent versions of Chrome and in [Node.js 10](https://github.com/nodejs/node/blob/4d58c08865d7c996bb8cfbe15793443fd425410f/lib/assert.js#L138).

### To reproduce
```javascript
escodegen.generate({
  type: 'TryStatement',
  block: {
    type: 'BlockStatement',
    body: []
  },
  handler: {
    type: 'CatchClause',
    param: null,
    body: {
      type: 'BlockStatement',
      body: []
    }
  },
  finalizer: null
})
```

### Output
```
/Users/ehdens/misc-oss/escodegen/escodegen.js:2446
        type = expr.type || Syntax.Property;
                    ^

TypeError: Cannot read property 'type' of null
    at CodeGenerator.generateExpression (/Users/ehdens/misc-oss/escodegen/escodegen.js:2446:21)
    at /Users/ehdens/misc-oss/escodegen/escodegen.js:1181:26
    at withIndent (/Users/ehdens/misc-oss/escodegen/escodegen.js:574:9)
    at CodeGenerator.CatchClause (/Users/ehdens/misc-oss/escodegen/escodegen.js:1176:13)
    at CodeGenerator.generateStatement (/Users/ehdens/misc-oss/escodegen/escodegen.js:2465:33)
    at CodeGenerator.TryStatement (/Users/ehdens/misc-oss/escodegen/escodegen.js:1526:52)
    at CodeGenerator.generateStatement (/Users/ehdens/misc-oss/escodegen/escodegen.js:2465:33)
    at generateInternal (/Users/ehdens/misc-oss/escodegen/escodegen.js:2486:28)
    at Object.generate (/Users/ehdens/misc-oss/escodegen/escodegen.js:2554:18)
    at Object.<anonymous> (/Users/ehdens/misc-oss/escodegen/demo.js:3:24)
```

### Expected Output
```javascript
try {
} catch {
}
```

**Comment by sanex3339** [comment]
Support un master now
