### ISSUE TITLE
cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by jatin273** [estools/escodegen#392]
Objectpattern Node doesnt have  key 'value'. 
<img width="567" alt="Screen Shot 2019-06-04 at 2 30 45 PM" src="https://user-images.githubusercontent.com/50847203/58908122-60b2d700-86d5-11e9-81fa-a200093d8dce.png">

at CodeGenerator.ObjectPattern (../node_modules/escodegen/escodegen.js:2220:36)
    at CodeGenerator.generateExpression (../node_modules/escodegen/escodegen.js:2456:28)
    at CodeGenerator.generatePattern (../node_modules/escodegen/escodegen.js:886:21)
    at CodeGenerator.generateFunctionParams (../node_modules/escodegen/escodegen.js:910:38)
    at CodeGenerator.generateFunctionBody (../node_modules/escodegen/escodegen.js:934:23)
    at CodeGenerator.ArrowFunctionExpression (../node_modules/escodegen/escodegen.js:1805:38)
    at CodeGenerator.generateExpression (../node_modules/escodegen/escodegen.js:2456:28)
    at CodeGenerator.generateAssignment (../node_modules/escodegen/escodegen.js:1002:22)
    at CodeGenerator.AssignmentExpression (../node_modules/escodegen/escodegen.js:1801:25)
    at CodeGenerator.generateExpression (../node_modules/escodegen/escodegen.js:2456:28)

**Comment by papandreou** [comment]
@jatin273, this is not a reproducible test case. Could you show a (minimal) valid ast that causes this error?

**Comment by bbjay** [comment]
this is being fixed in PR #408
hopefully it will be merged soon

**Comment by takahser** [comment]
any news on when #408 is going to be fixed?

**Comment by sanex3339** [comment]
Fixed
